apiVersion: v1
kind: PersistentVolume
metadata:
  name: sitio-web-pv
spec:
  storageClassName: mi-clase
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/linux-pc/Escritorio/ATK8s/web" 
