apiVersion: v1
kind: PersistentVolume
metadata:
  name: sitio-web-pv-mount
spec:
  storageClassName: mi-clase
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/sitio-web
